---

- name: Create user group
  group: name={{ user.group }} state=present

- name: Create user and assign to group
  user: name={{ user.name }} group={{ user.group }} uid={{ user.uid }} password={{ user.name | password_hash('sha512') }} shell={{ user.shell }} update_password=on_create
  register: newuser

- name: Force user to change password
  shell: chage -d 0 {{ user.name }}
  when: newuser.changed

- name: Create user log dir
  file: path=/home/{{ user.name }}/{{ user.log_dir }} state=directory owner={{ user.name }} group={{ user.group }}
  when: user.log_dir is defined

- name: Push logrotate config for user logs
  template: src=logrotate.j2 dest=/etc/logrotate.d/user
  when: user.log_dir is defined


