---
- name: Install VirtualBox and dependencies
  pacman: name={{ item }} state=present
  with_items:
    - net-tools
    - virtualbox-host-dkms
    - virtualbox
    - virtualbox-guest-iso
    - virtualbox-guest-utils


- name: Add the user to vboxusers group
  user: name={{ user.name }} groups=vboxusers append=yes
