---
- name: Install universal base packages
  pacman: name={{ item }} state=present
  with_items: "{{ base_packages }}"

- name: Install videodrivers
  pacman: name={{ item }} state=present
  with_items: "{{ video_drivers }}"

- name: Install X and DE
  pacman: name={{ item }} state=present
  with_items:
    - xf86-input-libinput
    - sddm    
    - xorg-server
    - xorg-xinit
    - plasma
    - ttf-freefont
    - spectacle

- name: Install media apps
  pacman: name={{ item }} state=present
  with_items:
    - gimp
    - mpv
    - deadbeef
    - perl-image-exiftool

- name: Install misc media codecs and helpers
  pacman: name={{ item }} state=present
  with_items:
    - flac
    - lame
    - exiv2

- name: Install desktop apps
  pacman: name={{ item }} state=present
  with_items:
    - firefox
    - chromium
    - scite
    - qbittorrent
    - kde-applications

- name: Install NetworkManager and applet
  pacman: name={{ item }} state=present
  with_items:
      - networkmanager
      - plasma-nm

- name: Enable and start NetworkManager
  service: name={{ item }} enabled=yes
  with_items:
    - NetworkManager.service
    - NetworkManager-dispatcher.service

    
- include: install-virtualbox.yml
