---

- name: Create pacman hook directory
  file: path=/etc/pacman.d/hooks state=directory

- name: Push pacman mirror list update hook
  copy: src=mirrorlist.hook dest=/etc/pacman.d/hooks/mirrorlist_update.hook

- name: Push pacman cache cleanup hook
  copy: src=paccache.hook dest=/etc/pacman.d/hooks/paccache_cleanup.hook

- name: Enable color in /etc/pacman.conf
  replace: dest=/etc/pacman.conf regexp='^#Color$' replace='Color'

- name: Install reflector
  pacman: name=reflector state=present

- name: Update of mirrorlist (via hook)
  command: pacman --noconfirm -S pacman-mirrorlist
  when: pacman_update_mirrors_and_cache == 'y'

- name: Enable multilib repo in /etc/pacman.conf
  blockinfile:
    dest: /etc/pacman.conf
    insertbefore: ^#.*multilib
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: Update_cache and after mirrorlist update
  command: pacman -Syy 
  when: pacman_update_mirrors_and_cache == 'y'

