---
- name: Create pacman hook directory
  file: path=/etc/pacman.d/hooks state=directory

- name: Push pacman mirror list update hook
  copy: src=mirrorlist.hook dest=/etc/pacman.d/hooks/mirrorlist_update.hook

- name: Push pacman cache cleanup hook
  copy: src=paccache.hook dest=/etc/pacman.d/hooks/paccache_cleanup.hook

- name: enable color in /etc/pacman.conf
  replace: dest=/etc/pacman.conf regexp='^#Color$' replace='Color'

- name: Add user to wheel group
  user: name={{ user.name }} groups=wheel append=yes

- name: Copy sudo configuration
  template: src=sudoers_wheel.j2 dest=/etc/sudoers.d/wheel mode=440 validate='visudo -cf %s'

- name: Enable services
  service: name={{ item }} enabled=yes
  with_items:
    - dhcpd.service 

