---

- stat: path={{ android_studio_bin_folder }}
  register: android_studio_bin_dir

- include: android_studio.yml
  when: not android_studio_bin_dir.stat.exists

- name: Create group for android-sdk users
  group: name=androidsdkusers state=present

- name: Add user to androidsdkusers group
  user: name={{ user.name }} groups=androidsdkusers append=yes


- name: Create Android SDK folder
  file:
    path: "{{ android_sdk_folder }}"
    state: directory

- name: Install packages for android dev
  pacman: name={{ item }} state=present
  with_items:
    - lib32-libstdc++5
    - lib32-zlib
    - mesa-demos  #needed for AVD


- name: Add Android-related env variables to ~/.pam_environment
  blockinfile:
    dest: /home/{{ user.name }}/.pam_environment
    create: yes
    marker: "### {mark} ANSIBLE MANAGED BLOCK :: Android variables"
    owner: "{{ user.name}}"
    group: "{{ user.group }}"
    block: |
        ANDROID_HOME={{ android_home }}
        #workaround for bug 'libGL error: failed to load driver' (https://code.google.com/p/android/issues/detail?id=197254)
        ANDROID_EMULATOR_USE_SYSTEM_LIBS=1



