---

- hosts: localhost
  become: yes
  roles:
    - base
    - { role: laptop, when: ansible_form_factor == 'Notebook' }
    - java-development
    - dotfiles
    - { role: microcode, when: "'GenuineIntel' in ansible_processor" }

  vars_prompt:
    - name: pacman_update_mirrors_and_cache
      prompt: "Update pacman mirrors and cache [y/N]?"
      private: no
      default: "N"
