---
- name: Install universal base packages
  pacman: name={{ item }} state=present
  with_items: "{{ base_packages }}"

- name: Install videodrivers
  pacman: name={{ item }} state=present
  with_items: "{{ video_drivers }}"

- name: Install sddm
  pacman: name={{ item }} state=present
  with_items:
    - sddm
  notify:
    - enable sddm

- name: Install X and DE
  pacman: name={{ item }} state=present
  with_items:
    - xf86-input-libinput
    - xorg-server
    - xorg-xinit
    - plasma
    - kde-applications 
    - kdegraphics-okular
    - kolourpaint
    - spectacle
    - gwenview
    - ttf-freefont


- name: Install media packages
  pacman: name={{ item }} state=present
  with_items:
    - gimp
    - mpv
    - deadbeef


- name: Install misc media codecs and helpers
  pacman: name={{ item }} state=present
  with_items:
    - flac
    - lame
    - exiv2
    - perl-image-exiftool


- name: Install utilities and misc soft
  pacman: name={{ item }} state=present
  with_items:
    - firefox
    - chromium
    - scite
    - qbittorrent